## ألوان أساسية 
foreground              #333333
background              #F5F5F5
selection_foreground    #F5F5F5
selection_background    #333333

## لوحة ألوان 
color0                  #555555
color1                  #D44950
color2                  #5D9E5D
color3                  #D9A65A
color4                  #4A89DC
color5                  #967ADC
color6                  #5DAEBD
color7                  #888888
color8                  #777777
color9                  #D44950
color10                 #5D9E5D
color11                 #D9A65A
color12                 #4A89DC
color13                 #967ADC
color14                 #5DAEBD
color15                 #AAAAAA

## ألوان المؤشر
cursor                  #333333
cursor_text_color       #F5F5F5
