# --- التشغيل التلقائي ---
exec-once = waybar & mako & hypridle & swww-daemon &
exec-once = nm-applet & blueman-applet &
exec-once = wl-paste --watch cliphist store &
exec-once = ~/.config/Scripts/udiskie-smart.sh &
exec-once = systemctl --user start hyprpolkitagent
exec-once = ~/.config/rofi/Scripts/clipboard_manager.sh --daemon



